spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DATABASE:nearby_beer}
    username: '${POSTGRES_USER:ze_delivery}'
    password: '${POSTGRES_PASSWORD:s3cr3t}'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
          temp.use_jdbc_metadata_defaults: false
          dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    baseline-description: schema_history_definitions

---
spring:
  profiles: test
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DATABASE:nearby_beer_test}
    username: '${POSTGRES_USER:ze_delivery}'
    password: '${POSTGRES_PASSWORD:s3cr3t}'
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false